version: 2.1

jobs:
  build:
    macos:
      xcode: 15.3.0
    resource_class: macos.m1.medium.gen1
    steps:
      - checkout
      - run:
          name: pod install
          command: |
            cd SwrveSDKTest
            pod install
      - run: fastlane unitTestsiOS scheme:"SwrveSDKiOS" device:"iPhone 15"
      - run: fastlane unitTeststvOS scheme:"SwrveSDKtvOS"
      - store_test_results:
          path: fastlane/test_output/

workflows:
  build_and_test:
    jobs:
      - build
