sources:
  - ../../public
templates:
  - Templates/AutoMockable.stencil
output:
    path: SDKTests/iOS/Swift/Generated
    link:
        project: SwrveSDKTest.xcodeproj
        target: SwrveSDK-iOSTests
        group: SDKTests/iOS/Swift/Generated

